spring.application.name=Nurix-Assignment

spring.datasource.url=jdbc:postgresql://localhost:5432/nurix_db
spring.datasource.username=nurix_user
spring.datasource.password=nurix_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
